### ISSUE TITLE
Stuck on hackazon setup

### ISSUE THREAD

**Issue by edrdo** [Newlode/hackazon#1]
Hello,

I have been trying to use your hackzon container.  I was also able to start the container without problems. However, I'm stuck on the "Hackazon Installation Wizard". I try to setup the admin password ("Admin Credentials") to no avail. I choose a password, confirm it, and click "Next Step" but the setup does not really progress to the next step (check the screenshot below). I get this behavior both on Linux and MacOS. 

<img width="400" alt="hackazon-screenshot" src="https://user-images.githubusercontent.com/1699245/31391871-a68bd28a-adcf-11e7-8eba-72a9af36a86c.png">

I use the following command line to start the container:
    
     docker run --name hackazon -p 8080:80 -p 8443:443 --rm -i -a stdin -a stdout -t pierrickv/hackazon:latest`

When starting the container, I get the following output (nothing seems to be wrong; I guess the ServerName warning is not significant).

     AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
     AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
       [Tue Oct 10 14:30:59.531654 2017] [mpm_prefork:notice] [pid 7] AH00163: Apache/2.4.10 (Debian) PHP/5.6.31 configured -- resuming normal operations
       [Tue Oct 10 14:30:59.531737 2017] [core:notice] [pid 7] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'

Best,
Eduardo

**Comment by PierrickV** [comment]
Hello,

I just saw your issue, sorry for that..

You have to use `docker-compose up`  to start the project otherwise the database will not be started (see docker-compose.yml).

This information is now in the README.
